# Generated by Django 3.0.7 on 2024-06-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasebilldetails',
            name='billno',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='billno',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='salebill',
            name='address',
        ),
        migrations.RemoveField(
            model_name='salebill',
            name='email',
        ),
        migrations.RemoveField(
            model_name='salebill',
            name='gstin',
        ),
        migrations.RemoveField(
            model_name='salebilldetails',
            name='cess',
        ),
        migrations.RemoveField(
            model_name='salebilldetails',
            name='cgst',
        ),
        migrations.RemoveField(
            model_name='salebilldetails',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='salebilldetails',
            name='eway',
        ),
        migrations.RemoveField(
            model_name='salebilldetails',
            name='igst',
        ),
        migrations.RemoveField(
            model_name='salebilldetails',
            name='po',
        ),
        migrations.RemoveField(
            model_name='salebilldetails',
            name='sgst',
        ),
        migrations.RemoveField(
            model_name='salebilldetails',
            name='tcs',
        ),
        migrations.RemoveField(
            model_name='salebilldetails',
            name='veh',
        ),
        migrations.AddField(
            model_name='salebill',
            name='mode_of_payment',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Momo', 'Momo')], default='Cash', max_length=10),
        ),
        migrations.AddField(
            model_name='salebill',
            name='sales_agent',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salebill',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='salebill',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.DeleteModel(
            name='PurchaseBill',
        ),
        migrations.DeleteModel(
            name='PurchaseBillDetails',
        ),
        migrations.DeleteModel(
            name='PurchaseItem',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
