# Generated by Django 3.0.7 on 2024-06-20 20:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20240617_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='perprice',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
